package view.components;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import javax.swing.JPanel;
import java.awt.RenderingHints;

/**
 *
 * @author rowan
 */
public class GradientPanel extends JPanel {
    private String gradientTop; //
    private String gradientBottom; //
    private int roundCorners;
    
    /**
     * Constructors:
     */
    public GradientPanel() {
        this( new FlowLayout(), 0 );
    }

    public GradientPanel(int roundCorners) {
        this( new FlowLayout(), roundCorners );
    }
    
    public GradientPanel(LayoutManager layout) {
        //def colors: top: Bright ocean green/teal color, bottom: Bold orange     
        this( layout, "#ccffcc", "#ff962e", 0 );                                   
    }

    public GradientPanel(LayoutManager layout, int roundCorners) {
        //def colors: top: Bright ocean green/teal color, bottom: Bold orange     
        this( layout, "#ccffcc", "#ff962e", roundCorners );                                   
    }
    
    public GradientPanel(String Top, String Bottom) {
        this( new FlowLayout(), Top, Bottom, 0 );
    }

    public GradientPanel(String Top, String Bottom, int roundCorners) {
        this( new FlowLayout(), Top, Bottom, roundCorners );
    }
    
    public GradientPanel(LayoutManager layout, String Top, String Bottom, int roundCorners) {
        super(layout, true); //use "double buffering" - takes more mem, smoother rendering
        initComponents();
        setOpaque(false); //Sets the background *BEHIND* the gradient to transparent
        this.gradientTop = Top;
        this.gradientBottom = Bottom;
        this.roundCorners = roundCorners;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintChildren(Graphics grphcs){
        Graphics2D g2 = (Graphics2D)grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g=new GradientPaint(0, 0, Color.decode(gradientTop), 0, getHeight(), Color.decode(gradientBottom));
        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), roundCorners, roundCorners);
        
        super.paintChildren(grphcs);
    }

    public String getGradientTop() {
        return gradientTop;
    }

    public void setGradientTop(String gradientTop) {
        this.gradientTop = gradientTop;
    }

    public String getGradientBottom() {
        return gradientBottom;
    }

    public void setGradientBottom(String gradientBottom) {
        this.gradientBottom = gradientBottom;
    }

    public int getRoundCorners() {
        return roundCorners;
    }

    public void setRoundCorners(int roundCorners) {
        this.roundCorners = roundCorners;
    }
    
    public void setGradient(String gradientTop, String gradientBottom) {
        this.gradientTop = gradientTop;
        this.gradientBottom = gradientBottom;
    }

    public void setGradientCorners(String gradientTop, String gradientBottom, int roundCorners) {
        this.gradientTop = gradientTop;
        this.gradientBottom = gradientBottom;
        this.roundCorners = roundCorners;
    }
    
    /**
     * Getters and Setters
     */
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
