//
package view.components;
//
//import view.models.Card;

import view.models.Card;

//import java.awt.BorderLayout;
//import java.awt.Color;
//import java.awt.Component;
//import java.awt.Dimension;
//import java.awt.Font;
//import java.awt.Graphics;
//import java.awt.Graphics2D;
//import java.awt.RenderingHints;
//import javax.swing.BorderFactory;
//import javax.swing.JLabel;
//import javax.swing.JList;
//import javax.swing.JSeparator;
//import javax.swing.SwingConstants;
//import view.models.RoImageIcon;
//
///**
// *
// * @author c0350261
// */
public class MenuCard extends Card {
////    private JLabel lblIcon = new JLabel();
////    private JLabel lblTitle = new JLabel();
//    private JSeparator separator = new JSeparator();
//    private JLabel label;
//    private boolean selected;
//    private Color selectColor;
//    /**
//     * Creates new form MenuCard
//     */
//    public MenuCard() {
//        initComponents();
//        setLayout( new BorderLayout( 10,0 ));
//        setBorder(BorderFactory.createEmptyBorder(10, 22, 10, 12));
//        setOpaque(false);
//        
//        lblTitle.setVerticalAlignment(SwingConstants.CENTER);
//        
//        add(lblIcon, BorderLayout.WEST);
//        add(lblTitle, BorderLayout.CENTER);
//
//        lblIcon.setOpaque(false);
//        lblTitle.setOpaque(false);   
//        
//        separator.setOpaque(false);
//        separator.setBorder(BorderFactory.createEmptyBorder(0, 20, 0, 20));
//    }
//    
//    
//    
//    public void makeContents(boolean isSelected, boolean cellHasFocus) {
//        
//        //Card contents
//        //----------Separator--------------
//    if (value.getType() == Model_MenuItem.MenuType.SEPARATOR) {
//        separator.setPreferredSize(new Dimension(1, 10));   // adjust height here
//        return separator;
//    }
//    //------------------Header----------------
//    if (value.getType() == Model_MenuItem.MenuType.HEADER) { 
//        label = new JLabel( value.getName() );
//        label.setFont( new Font( "Segoe UI", Font.BOLD, 24));
//        label.setHorizontalAlignment( SwingConstants.CENTER );
//        
//        return label;
//    } 
//    //-----------------With Icon---------------------
//    else { setDataWIcon( value ); }
//    setSelected( isSelected , list);
//
//    //card spacing
//    setBorder( BorderFactory.createCompoundBorder( 
//            BorderFactory.createEmptyBorder(6,8,6,8),
//            BorderFactory.createLineBorder( new Color(230, 230, 230) )
//    ) );
////        list.setFixedCellHeight( 70 ); //row height
//        //hover        // ... maybe later. fair bit here
//        setPreferredSize( new Dimension(1, 70) );
//        return this;
//} 
//
////    public void setDataWIcon( Model_MenuItem value ) {
////        System.out.println("dataWIcon: " + value.getType() );
////        System.out.println("dataWIcon: " + value.getName());
////        lblTitle.setFont(new Font("URW Bookman", Font.BOLD, 32));
////        lblTitle.setText(value.getName());
////
////        RoImageIcon icon = (RoImageIcon) value.toRoImageIcon();
////        lblIcon.setIcon(icon.scaleIconYFontY(lblTitle));
////    }
//    
//    public void setData( Model_MenuItem value ) {
//        lblTitle.setFont(new Font("URW Bookman", Font.BOLD, 32));
//        lblTitle.setText(value.getName());
////        lblIcon.setIcon(null);        
////        lblIcon.setIcon(null);        
//    }
//    
////    public void setSelected(boolean selected, JList<?> list) {
////        this.selected = selected;
////        if (selected) {
////            setBackground(list.getSelectionBackground());
////            lblTitle.setForeground( Color.BLACK );
////        } else {
////            setBackground( list.getBackground());
////            lblTitle.setForeground( list.getForeground());            
////        }
////    }
//
////    @Override
////    protected void paintComponent(Graphics grphcs) {
////        Graphics2D g2 = (Graphics2D) grphcs.create();
////        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
////
////        if (selected) {
////            if ( selectColor == null ) {
////                g2.setColor(new Color(189,238,239,80) );
////            } else {
////                g2.setColor( selectColor );
////            }
////            g2.fillRoundRect(8, 0, getWidth()-16, getHeight(), 8, 8);
////        }
////        g2.dispose();
////        super.paintComponent(grphcs);
////    }    
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitle.setText("temp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblTitle)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
