package view.components;

import controller.AppContext;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;
import model.User;
import model.gui.Model_MenuItem;
import view.ViewCustomerGUI;
import view.ViewDestinationsGUI;
import view.ViewTripFrame;

/**
 *
 * @author rowan
 */
public class MenuCustomer extends GradientPanel {
        Color topColor;
        Color bottomColor;
        Color selectColor;
//        private AppContext context;
        private AppWindow topView;

    /**
     * Creates new form MenuCustomer
     */
    public MenuCustomer( ) {}
    
    public MenuCustomer( AppContext context ) {
        super(new Color(204,255,204), new Color( 255,150,46 ), 0);
        initComponents();
        listMenuCustomer.setOpaque(false);
        init( );
    }
    
    //getters and setters

//    public AppContext getContext() { return context; }
//    public void setContext(AppContext context) { 
//        this.context = context;
//        refreshView();
//    }

    public AppWindow getTopView() { return topView; }
    public void setTopView(AppWindow topView) { 
        this.topView = topView; 
    }

    public JLabel getLblLogo() { return lblLogo; }
    public void setLblLogo(JLabel lblLogo) {
        this.lblLogo = lblLogo;
    }

    public ListMenu getListMenuCustomer() { return listMenuCustomer; }
    public void setListMenuCustomer(ListMenu listMenuCustomer) {
        this.listMenuCustomer = listMenuCustomer;
    }

    public JPanel getPnlLogo() { return pnlLogo; }
    public void setPnlLogo(JPanel pnlLogo) {
        this.pnlLogo = pnlLogo;
    }
    
    
    
//    public void setBasics(AppWindow topView, AppContext context) {
//        this.topView = topView;
//        this.context = context;
//    }

//    public ListMenu<String> getListMenuCustomer() {
//        return listMenuCustomer;
//    }
//
//    public void setListMenuCustomer(ListMenu<String> listMenuCustomer) {
//        this.listMenuCustomer = listMenuCustomer;
//    }
    

// FUNCTIONAL
    private void init() {}
//                
//            case default:
//                throw new InvalidAttributeValueException("there is a problem with the user role");




    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        listMenuCustomer = new view.components.ListMenu();

        pnlLogo.setOpaque(false);

        lblLogo.setFont(new java.awt.Font("URW Bookman", 1, 36)); // NOI18N
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/graphics/travelBug70.png"))); // NOI18N
        lblLogo.setText("Travel Bug");

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        listMenuCustomer.setBackground(new java.awt.Color(242, 242, 242));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listMenuCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listMenuCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

//    @Override
//    protected void paintChildren(Graphics grphcs){
//        Graphics2D g2 = (Graphics2D)grphcs;
//        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
//        GradientPaint g=new GradientPaint(0, 0, Color.decode(gradientTop), 0, getHeight(), Color.decode(gradientBottom));
//        g2.setPaint(g);
    ////        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
//        g2.fillRect(0, 0, getWidth(), getHeight());
//        
//        super.paintChildren(grphcs);
//    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLogo;
    private view.components.ListMenu listMenuCustomer;
    private javax.swing.JPanel pnlLogo;
    // End of variables declaration//GEN-END:variables
}
