
package view.components;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import static java.awt.Font.BOLD;
import static java.awt.Font.ITALIC;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.BorderFactory;
import javax.swing.JPanel;

/**
 *
 * @author rowan
 */
public class MenuItem extends JPanel {
    
//    private boolean selected;
//
//    public MenuItem(Model_MenuItem data) {
//        initComponents();
//        setBorder( javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10) );
//        lblMenu.setBorder( BorderFactory.createEmptyBorder(0, 10, 0, 0));
//        setOpaque(false);
//
//        if ( data.getType() == Model_MenuItem.MenuType.MENU ) {
//            lblMenu.setText(data.getName());
//            lblMenu.setFont(new Font( null , 1, 24));
//            lblIcon.setIcon(data.scaleIconByText(lblMenu, "travelBug70") );
//        } else if (data.getType() == Model_MenuItem.MenuType.HEADER) {
//            lblIcon.setText(data.getName());
//            lblIcon.setFont(new Font( null , 1, 24));
//            lblMenu.setVisible(false);
//        } else {
//            lblMenu.setText(" ");
//        }
//
//        lblMenu.setPreferredSize(null);
//        lblMenu.revalidate();
//    }
//
//    public void setSelected(boolean selected) {
//        this.selected = selected;
//        repaint();
//    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblIcon = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(32767, 200));
        setMinimumSize(new java.awt.Dimension(0, 35));
        setPreferredSize(null);
        setLayout(new java.awt.BorderLayout());
        add(lblIcon, java.awt.BorderLayout.LINE_START);

        lblMenu.setText("Menu Item");
        lblMenu.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblMenu.setMaximumSize(new java.awt.Dimension(150, 1600));
        lblMenu.setPreferredSize(new java.awt.Dimension(150, 16));
        add(lblMenu, java.awt.BorderLayout.CENTER);
    }// </editor-fold>                        

//    @Override
//    protected void paintComponent(Graphics grphcs) {
//        if (selected) {
//            Graphics2D g2 = (Graphics2D)grphcs;
//            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
//            g2.setColor(new Color(255,255,255,80) );
//            g2.fillRoundRect(10, 0, getWidth()-20, getHeight(), 5, 5);
//        }
//        
//        super.paintComponent(grphcs);
//    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblMenu;
    // End of variables declaration                   
}