/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.components;

/**
 *
 * @author C0350261
 */
public class MenuLogo extends javax.swing.JPanel {

    /**
     * Creates new form MenuLogo
     */
    public MenuLogo() {
        initComponents();
        lblLogo.setFont(new java.awt.Font("URW Bookman", 1, 36));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        model_lblScales1 = new view.models.Model_lblScales();

        setLayout(new java.awt.BorderLayout());

        lblLogo.setFont(new java.awt.Font("URW Bookman", 1, 36)); // NOI18N
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/graphics/travelBug70.png"))); // NOI18N
        lblLogo.setText("Travel Bug");
        add(lblLogo, java.awt.BorderLayout.CENTER);

        model_lblScales1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/graphics/travelBug70.png"))); // NOI18N
        model_lblScales1.setText("Travel Bug");
        add(model_lblScales1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLogo;
    private view.models.Model_lblScales model_lblScales1;
    // End of variables declaration//GEN-END:variables
}
