package utility;

import java.awt.event.ActionListener;
import view.components.PanelBorder;
import view.dashboard.DashboardCustomer;

/**
 *
 * @author rowan
 */
public class AppWindowCust extends GenericView {
    private AppContext context;
    
    public AppWindowCust( AppContext context ) {
        super( context );
        initComponents();
        pnlDashCust.revalidate();
        pnlDashCust.repaint();
        
//        this.session = session;
//        setBackground( new Color(0, 0, 0, 0) ); //only works with undecorated frame
    }
    
     //Getter and Setters

    public DashboardCustomer getDashboardList() {
        return pnlDashCust;
    }

    public void setDashboardList(DashboardCustomer pnlDashCust) {
        this.pnlDashCust = pnlDashCust;
    }

    public AppContext getContext() {
        return context;
    }

    public void setContext(AppContext context) {
        this.context = context;
    }

    public PanelBorder getPnlAppWindow() {
        return pnlDashWind;
    }

    public void setPnlAppWindow(PanelBorder pnlAppWindow) {
        this.pnlDashWind = pnlAppWindow;
    }

    public DashboardCustomer getPnlDashCust() {
        return pnlDashCust;
    }

    public void setPnlDashCust(DashboardCustomer pnlDashCust) {
        this.pnlDashCust = pnlDashCust;
    }

    public PanelBorder getPnlDashWind() {
        return pnlDashWind;
    }

    public void setPnlDashWind(PanelBorder pnlDashWind) {
        this.pnlDashWind = pnlDashWind;
    }
    
    // ---------------Listeners--------------------------
    //----------------Customer Section-------------------
    public void addListenerToBtnCustProfile( ActionListener loginListener ) {               
        getPnlDashCust().getPnlDashCust().getBtnCustProfile().addActionListener( loginListener ); }
    public void addListenerToBtnSearchDest( ActionListener loginListener ) {
        getPnlDashCust().getPnlDashCust().getBtnSearchDest().addActionListener( loginListener ); }
    public void addListenerToBtnLatestBooking( ActionListener loginListener ) {
        getPnlDashCust().getPnlDashCust().getBtnLatestBooking().addActionListener( loginListener ); }
    public void addListenerToBtnAllBooking( ActionListener loginListener ) {
        getPnlDashCust().getPnlDashCust().getBtnViewBooking().addActionListener( loginListener ); }
    public void addListenerToLogoutCust( ActionListener loginListener ) {
        getPnlDashCust().getBtnLogout().addActionListener( loginListener ); }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDashWind = new view.components.PanelBorder();
        pnlDashCust = new view.dashboard.DashboardCustomer();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout pnlDashWindLayout = new javax.swing.GroupLayout(pnlDashWind);
        pnlDashWind.setLayout(pnlDashWindLayout);
        pnlDashWindLayout.setHorizontalGroup(
            pnlDashWindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDashWindLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlDashCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlDashWindLayout.setVerticalGroup(
            pnlDashWindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDashCust, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDashWind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDashWind, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> {
//            
//            AppContext session = new AppContext();
//            AppWindowCust app = new AppWindowCust( session );
//            app.setVisible(true);
//            
//            /*temporary while working on things - add user GUI */
//            AddUserGUIPage1 view = new AddUserGUIPage1();
//            UserDAO userDao = new UserDAO();
//            UserControl userControl = new UserControl( userDao, view );
//            
//            view.setVisible(true);
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.dashboard.DashboardCustomer pnlDashCust;
    private view.components.PanelBorder pnlDashWind;
    // End of variables declaration//GEN-END:variables
}
