/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Template_ControllerAndRelatedElsewhere;

import java.awt.event.ActionListener;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionListener;
import view.components.ListMenu;

/**
 *
 * @author C0350261
 */
public class FrameGUITemplate extends javax.swing.JFrame {

    /**
     * Creates new form FrameGUITemplate
     */
    public FrameGUITemplate() { 
        initComponents(); //Leave alone, Leave last
        
//        //some common options:
//        this.setSize(xInt,yInt);
//        this.setLocationRelativeTo( null ); // centers the window on opening
//        this.setResizable( false ); // makes non-resizable
    }
    
    //IMPORTANT: define getters and setters
//    // Make getters and setters for ALL components - INCLUDING subViews

    public PanelDemo getPanelDemo1() { return panelDemo1; }
    public void setPanelDemo1(PanelDemo panelDemo1) { this.panelDemo1 = panelDemo1; }
    // note that just calling the panel, not the contents of the panel
    // panel needs to have its own getters and setters for the items within
    // may also opt to add helpers to reach into the panels, so you dont 
            // have to chain the commands as much but its not needed
    
    public JTextField getjTextField1() { return jTextField1; }
    public void setjTextField1(JTextField jTextField1) { this.jTextField1 = jTextField1; }

//    public ListMenu<String> getListMenuCustomer() {
//        return listMenuCustomer;
//    }
//
//    public void setListMenuCustomer(ListMenu<String> listMenuCustomer) {
//        this.listMenuCustomer = listMenuCustomer;
//    }
   
    
    
    //IMPORTAMT: define listener functions (...should be in panel and then these as helpers, but going to chain here for ease)
//    //eg
    public void addItemLIsOnListener( ActionListener loginListener ) {
        panelDemo1.getjButton1().addActionListener( loginListener );
    }
    public void addItemL2IsOnListener( ListSelectionListener listListener ) {
        panelDemo1.getjList1().addListSelectionListener(listListener );
    }
    
    
    
    
    //IMPORTANT - Remove Main auto generated below the @SuppressWarnings section
            //only The one 'Main' Class should have a main.
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDemo1 = new Template_ControllerAndRelatedElsewhere.PanelDemo();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));

        panelDemo1.setBackground(new java.awt.Color(204, 255, 204));

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDemo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(panelDemo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//REMOVE ALL THIS STUFF
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrameGUITemplate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrameGUITemplate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrameGUITemplate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrameGUITemplate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrameGUITemplate().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private Template_ControllerAndRelatedElsewhere.PanelDemo panelDemo1;
    // End of variables declaration//GEN-END:variables
}