/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import model.*;

/**
 *
 * @author rowan
 */
public class DestinationsGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DestinationsGUI.class.getName());

    /**
     * Creates new form BookingsGUI
     */
    public DestinationsGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        pnlDestinationCombined = new javax.swing.JPanel();
        pnlHotel = new javax.swing.JPanel();
        txtHotelName = new javax.swing.JTextField();
        txtHotelStNum = new javax.swing.JTextField();
        txtHotelStreetAddress = new javax.swing.JTextField();
        txtHotelCity = new javax.swing.JTextField();
        txtRegion = new javax.swing.JTextField();
        txtPostalCode = new javax.swing.JTextField();
        txtCountry = new javax.swing.JTextField();
        txtRating = new javax.swing.JTextField();
        pnlTravel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTravelInfo = new javax.swing.JTextArea();
        txtTravelMethd = new javax.swing.JTextField();
        txtTransfer = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pnlActivities = new javax.swing.JPanel();
        txtActivitiesOption = new javax.swing.JTextField();
        lblActivities = new javax.swing.JLabel();
        txtActivitiesIncl = new javax.swing.JTextField();
        pnlActiveInfo = new javax.swing.JPanel();
        lblDate = new javax.swing.JLabel();
        lblDate1 = new javax.swing.JLabel();
        lblDate2 = new javax.swing.JLabel();
        lblDate3 = new javax.swing.JLabel();
        pnlDestination = new javax.swing.JPanel();
        pnlDestinationInfo = new javax.swing.JPanel();
        txtDestinationNotes = new javax.swing.JTextArea();
        lblDestinationName = new javax.swing.JLabel();
        lblDestinationCountry = new javax.swing.JLabel();
        pnlDestinationDays = new javax.swing.JPanel();
        lblDays = new javax.swing.JLabel();
        lblStay = new javax.swing.JLabel();
        lblNights = new javax.swing.JLabel();
        lblNumDays = new javax.swing.JTextField();
        lblNumNights = new javax.swing.JTextField();
        pnlPrices = new javax.swing.JPanel();
        txtActivityPrice = new javax.swing.JTextField();
        lblActivityPrice = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        txtActivityPrice1 = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtBasePrice = new javax.swing.JTextField();
        btnBookNow = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frameDestination"); // NOI18N

        pnlHotel.setBackground(new java.awt.Color(255, 204, 153));

        txtHotelName.setFont(new java.awt.Font("Noto Sans", 2, 12)); // NOI18N
        txtHotelName.setText("Hotel Name");
        txtHotelName.addActionListener(this::txtHotelNameActionPerformed);

        txtHotelStNum.setText("streen no");

        txtHotelStreetAddress.setText("street address");

        txtHotelCity.setText("hotel City");

        txtRegion.setText("province or region");
        txtRegion.setToolTipText("");

        txtPostalCode.setText("postal code");

        txtCountry.setText("Country");

        txtRating.setText("rating");

        javax.swing.GroupLayout pnlHotelLayout = new javax.swing.GroupLayout(pnlHotel);
        pnlHotel.setLayout(pnlHotelLayout);
        pnlHotelLayout.setHorizontalGroup(
            pnlHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHotelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHotelLayout.createSequentialGroup()
                        .addComponent(txtHotelStNum, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHotelStreetAddress))
                    .addGroup(pnlHotelLayout.createSequentialGroup()
                        .addGroup(pnlHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlHotelLayout.createSequentialGroup()
                                .addComponent(txtHotelName, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRating, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlHotelLayout.createSequentialGroup()
                                .addComponent(txtHotelCity, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlHotelLayout.setVerticalGroup(
            pnlHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHotelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHotelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHotelStNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHotelStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHotelCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlTravel.setBackground(new java.awt.Color(255, 204, 153));

        txtTravelInfo.setColumns(20);
        txtTravelInfo.setRows(5);
        txtTravelInfo.setText("travel info");
        jScrollPane2.setViewportView(txtTravelInfo);

        txtTravelMethd.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTravelMethd.setText("travel method");
        txtTravelMethd.addActionListener(this::txtTravelMethdActionPerformed);

        txtTransfer.setText("transfer details");

        jLabel1.setText("Travel");

        javax.swing.GroupLayout pnlTravelLayout = new javax.swing.GroupLayout(pnlTravel);
        pnlTravel.setLayout(pnlTravelLayout);
        pnlTravelLayout.setHorizontalGroup(
            pnlTravelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTravelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTravelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(pnlTravelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(191, 191, 191)
                        .addComponent(txtTravelMethd))
                    .addComponent(txtTransfer))
                .addContainerGap())
        );
        pnlTravelLayout.setVerticalGroup(
            pnlTravelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTravelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTravelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTravelMethd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlActivities.setBackground(new java.awt.Color(255, 204, 153));

        txtActivitiesOption.setText("optional activities");

        lblActivities.setText("Activities");

        txtActivitiesIncl.setText("included activities");

        javax.swing.GroupLayout pnlActivitiesLayout = new javax.swing.GroupLayout(pnlActivities);
        pnlActivities.setLayout(pnlActivitiesLayout);
        pnlActivitiesLayout.setHorizontalGroup(
            pnlActivitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActivitiesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlActivitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtActivitiesIncl)
                    .addGroup(pnlActivitiesLayout.createSequentialGroup()
                        .addComponent(lblActivities)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtActivitiesOption))
                .addContainerGap())
        );
        pnlActivitiesLayout.setVerticalGroup(
            pnlActivitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActivitiesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblActivities)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtActivitiesIncl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtActivitiesOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblDate.setText("todays date");

        lblDate1.setText("active Customer");

        lblDate2.setText("active Destination");

        lblDate3.setText("user Account");

        javax.swing.GroupLayout pnlActiveInfoLayout = new javax.swing.GroupLayout(pnlActiveInfo);
        pnlActiveInfo.setLayout(pnlActiveInfoLayout);
        pnlActiveInfoLayout.setHorizontalGroup(
            pnlActiveInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActiveInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlActiveInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActiveInfoLayout.createSequentialGroup()
                        .addComponent(lblDate1)
                        .addGap(65, 65, 65)
                        .addComponent(lblDate3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDate))
                    .addGroup(pnlActiveInfoLayout.createSequentialGroup()
                        .addComponent(lblDate2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlActiveInfoLayout.setVerticalGroup(
            pnlActiveInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActiveInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlActiveInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(lblDate1)
                    .addComponent(lblDate3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDate2)
                .addContainerGap())
        );

        pnlDestination.setBackground(new java.awt.Color(255, 204, 153));

        txtDestinationNotes.setColumns(20);
        txtDestinationNotes.setRows(5);
        txtDestinationNotes.setText("Destination Notes");

        lblDestinationName.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        lblDestinationName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDestinationName.setText("Destination Name");

        lblDestinationCountry.setFont(new java.awt.Font("Noto Sans", 2, 12)); // NOI18N
        lblDestinationCountry.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDestinationCountry.setText("country/region");

        javax.swing.GroupLayout pnlDestinationInfoLayout = new javax.swing.GroupLayout(pnlDestinationInfo);
        pnlDestinationInfo.setLayout(pnlDestinationInfoLayout);
        pnlDestinationInfoLayout.setHorizontalGroup(
            pnlDestinationInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDestinationInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDestinationInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtDestinationNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDestinationCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDestinationName, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlDestinationInfoLayout.setVerticalGroup(
            pnlDestinationInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDestinationInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDestinationName)
                .addGap(1, 1, 1)
                .addComponent(lblDestinationCountry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDestinationNotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblDays.setText("days &");

        lblStay.setText("Stay duration: ");

        lblNights.setText("nights");

        lblNumDays.setText("# days");
        lblNumDays.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblNumDays.addActionListener(this::lblNumDaysActionPerformed);

        lblNumNights.setText("# nights");

        javax.swing.GroupLayout pnlDestinationDaysLayout = new javax.swing.GroupLayout(pnlDestinationDays);
        pnlDestinationDays.setLayout(pnlDestinationDaysLayout);
        pnlDestinationDaysLayout.setHorizontalGroup(
            pnlDestinationDaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDestinationDaysLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStay)
                .addGap(18, 18, 18)
                .addComponent(lblNumDays, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDays)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumNights, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNights)
                .addContainerGap())
        );
        pnlDestinationDaysLayout.setVerticalGroup(
            pnlDestinationDaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDestinationDaysLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDestinationDaysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblStay)
                    .addComponent(lblDays)
                    .addComponent(lblNights)
                    .addComponent(lblNumDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumNights, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txtActivityPrice.setText("$price");

        lblActivityPrice.setText("activity fees:");

        lblTotalPrice.setText("Total Estimated Cost:");

        txtActivityPrice1.setText("$price");

        lblPrice.setText("base price:");

        txtBasePrice.setText("$price");

        javax.swing.GroupLayout pnlPricesLayout = new javax.swing.GroupLayout(pnlPrices);
        pnlPrices.setLayout(pnlPricesLayout);
        pnlPricesLayout.setHorizontalGroup(
            pnlPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPricesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPricesLayout.createSequentialGroup()
                        .addComponent(lblPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPricesLayout.createSequentialGroup()
                        .addComponent(lblActivityPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtActivityPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPricesLayout.createSequentialGroup()
                        .addComponent(lblTotalPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtActivityPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlPricesLayout.setVerticalGroup(
            pnlPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPricesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtBasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtActivityPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblActivityPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtActivityPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalPrice))
                .addContainerGap())
        );

        btnBookNow.setBackground(new java.awt.Color(204, 255, 204));
        btnBookNow.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        btnBookNow.setText("Book!");

        javax.swing.GroupLayout pnlDestinationLayout = new javax.swing.GroupLayout(pnlDestination);
        pnlDestination.setLayout(pnlDestinationLayout);
        pnlDestinationLayout.setHorizontalGroup(
            pnlDestinationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDestinationLayout.createSequentialGroup()
                .addGroup(pnlDestinationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDestinationLayout.createSequentialGroup()
                        .addGroup(pnlDestinationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDestinationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlDestinationLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(pnlDestinationInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDestinationLayout.createSequentialGroup()
                                    .addGap(115, 115, 115)
                                    .addComponent(pnlPrices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlDestinationLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pnlDestinationDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDestinationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBookNow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlDestinationLayout.setVerticalGroup(
            pnlDestinationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDestinationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDestinationInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDestinationDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPrices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBookNow)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDestinationCombinedLayout = new javax.swing.GroupLayout(pnlDestinationCombined);
        pnlDestinationCombined.setLayout(pnlDestinationCombinedLayout);
        pnlDestinationCombinedLayout.setHorizontalGroup(
            pnlDestinationCombinedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDestinationCombinedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDestinationCombinedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(pnlHotel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTravel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlActivities, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlActiveInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDestinationCombinedLayout.setVerticalGroup(
            pnlDestinationCombinedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDestinationCombinedLayout.createSequentialGroup()
                .addComponent(pnlActiveInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDestination, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlTravel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlActivities, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDestinationCombined, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDestinationCombined, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void txtTravelMethdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTravelMethdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTravelMethdActionPerformed

    private void txtHotelNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHotelNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHotelNameActionPerformed

    private void lblNumDaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblNumDaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNumDaysActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DestinationsGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookNow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblActivities;
    private javax.swing.JLabel lblActivityPrice;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDate1;
    private javax.swing.JLabel lblDate2;
    private javax.swing.JLabel lblDate3;
    private javax.swing.JLabel lblDays;
    private javax.swing.JLabel lblDestinationCountry;
    private javax.swing.JLabel lblDestinationName;
    private javax.swing.JLabel lblNights;
    private javax.swing.JTextField lblNumDays;
    private javax.swing.JTextField lblNumNights;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblStay;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JPanel pnlActiveInfo;
    private javax.swing.JPanel pnlActivities;
    private javax.swing.JPanel pnlDestination;
    private javax.swing.JPanel pnlDestinationCombined;
    private javax.swing.JPanel pnlDestinationDays;
    private javax.swing.JPanel pnlDestinationInfo;
    private javax.swing.JPanel pnlHotel;
    private javax.swing.JPanel pnlPrices;
    private javax.swing.JPanel pnlTravel;
    private javax.swing.JTextField txtActivitiesIncl;
    private javax.swing.JTextField txtActivitiesOption;
    private javax.swing.JTextField txtActivityPrice;
    private javax.swing.JTextField txtActivityPrice1;
    private javax.swing.JTextField txtBasePrice;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextArea txtDestinationNotes;
    private javax.swing.JTextField txtHotelCity;
    private javax.swing.JTextField txtHotelName;
    private javax.swing.JTextField txtHotelStNum;
    private javax.swing.JTextField txtHotelStreetAddress;
    private javax.swing.JTextField txtPostalCode;
    private javax.swing.JTextField txtRating;
    private javax.swing.JTextField txtRegion;
    private javax.swing.JTextField txtTransfer;
    private javax.swing.JTextArea txtTravelInfo;
    private javax.swing.JTextField txtTravelMethd;
    // End of variables declaration//GEN-END:variables
}
