/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import view.components.VSearchBarUsers;

/**
 *
 * @author c0541856
 */
public class FilterUsersGUI extends javax.swing.JFrame {

    /**
     * Creates new form UsersGUI
     */
    public FilterUsersGUI() {
        initComponents();
    }
    
    //getters and setters

    public JScrollPane getScrollUsers() {
        return scrollUsers;
    }

    public void setScrollUsers(JScrollPane scrollUsers) {
        this.scrollUsers = scrollUsers;
    }

    public JTable getTblUsers() {
        return tblUsers;
    }

    public void setTblUsers(JTable tblUsers) {
        this.tblUsers = tblUsers;
    }

    public VSearchBarUsers getvSearchBarUsers() {
        return vSearchBarUsers;
    }

    public void setvSearchBarUsers(VSearchBarUsers vSearchBarUsers) {
        this.vSearchBarUsers = vSearchBarUsers;
    }

    public JButton getBtnFocus() {
        return btnFocus;
    }

    public void setBtnFocus(JButton btnFocus) {
        this.btnFocus = btnFocus;
    }

    public JButton getBtnOpen() {
        return btnOpen;
    }

    public void setBtnOpen(JButton btnOpen) {
        this.btnOpen = btnOpen;
    }
    
    
    
    //Listeners
    public void addNewUserBtnListener(ActionListener nextListener) {
        vSearchBarUsers.getBtnNewUser().addActionListener(nextListener);
    }
    public void addSearchBtnListener(ActionListener nextListener) {
        vSearchBarUsers.getBtnSearch().addActionListener(nextListener);
    }
    public void addFocusBtnListener(ActionListener nextListener) {
        this.getBtnFocus().addActionListener(nextListener);
    }
    public void addOpenBtnListener(ActionListener nextListener) {
        this.getBtnOpen().addActionListener(nextListener);
    }
    //not 100% sure on how to get combo box and textfield values

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFilterUsers = new javax.swing.JPanel();
        scrollUsers = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        vSearchBarUsers = new view.components.VSearchBarUsers();
        btnFocus = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scrollUsers.setPreferredSize(new java.awt.Dimension(534, 260));

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "username", "First Name", "Last Name", "Role", "Phone", "Account Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollUsers.setViewportView(tblUsers);

        btnFocus.setBackground(new java.awt.Color(204, 255, 255));
        btnFocus.setText("Focus on Selected User");
        btnFocus.setMaximumSize(new java.awt.Dimension(151, 30));
        btnFocus.setMinimumSize(new java.awt.Dimension(151, 30));
        btnFocus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFocusActionPerformed(evt);
            }
        });

        btnOpen.setBackground(new java.awt.Color(255, 204, 153));
        btnOpen.setText("Open User");
        btnOpen.setMaximumSize(new java.awt.Dimension(151, 30));
        btnOpen.setMinimumSize(new java.awt.Dimension(151, 30));
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFilterUsersLayout = new javax.swing.GroupLayout(pnlFilterUsers);
        pnlFilterUsers.setLayout(pnlFilterUsersLayout);
        pnlFilterUsersLayout.setHorizontalGroup(
            pnlFilterUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFilterUsersLayout.createSequentialGroup()
                .addGroup(pnlFilterUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlFilterUsersLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFocus, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFilterUsersLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(pnlFilterUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollUsers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vSearchBarUsers, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE))))
                .addGap(38, 38, 38))
        );
        pnlFilterUsersLayout.setVerticalGroup(
            pnlFilterUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFilterUsersLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(vSearchBarUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlFilterUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFocus, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(btnOpen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFilterUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFilterUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFocusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFocusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFocusActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpenActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFocus;
    private javax.swing.JButton btnOpen;
    private javax.swing.JPanel pnlFilterUsers;
    private javax.swing.JScrollPane scrollUsers;
    private javax.swing.JTable tblUsers;
    private view.components.VSearchBarUsers vSearchBarUsers;
    // End of variables declaration//GEN-END:variables
}
