/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import view.subViews.VSearchBarUsers;

/**
 *
 * @author c0541856
 */
public class FilterUsersGUI extends javax.swing.JFrame {

    /**
     * Creates new form UsersGUI
     */
    public FilterUsersGUI() {
        initComponents();
    }
    
    //getters and setters

    public JScrollPane getScrollUsers() {
        return scrollUsers;
    }

    public void setScrollUsers(JScrollPane scrollUsers) {
        this.scrollUsers = scrollUsers;
    }

    public JTable getTblUsers() {
        return tblUsers;
    }

    public void setTblUsers(JTable tblUsers) {
        this.tblUsers = tblUsers;
    }

    public VSearchBarUsers getvSearchBarUsers() {
        return vSearchBarUsers;
    }

    public void setvSearchBarUsers(VSearchBarUsers vSearchBarUsers) {
        this.vSearchBarUsers = vSearchBarUsers;
    }
    
    
    
    //Listeners
    public void addNewUserBtnListener(ActionListener nextListener) {
        vSearchBarUsers.getBtnNewUser().addActionListener(nextListener);
    }
    public void addSearchBtnListener(ActionListener nextListener) {
        vSearchBarUsers.getBtnSearch().addActionListener(nextListener);
    }
    //not 100% sure on how to get combo box and textfield values

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFilterUsers = new javax.swing.JPanel();
        scrollUsers = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        vSearchBarUsers = new view.subViews.VSearchBarUsers();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scrollUsers.setPreferredSize(new java.awt.Dimension(534, 260));

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "username", "First Name", "Last Name", "Role", "Email", "Account Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollUsers.setViewportView(tblUsers);

        javax.swing.GroupLayout pnlFilterUsersLayout = new javax.swing.GroupLayout(pnlFilterUsers);
        pnlFilterUsers.setLayout(pnlFilterUsersLayout);
        pnlFilterUsersLayout.setHorizontalGroup(
            pnlFilterUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFilterUsersLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pnlFilterUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(vSearchBarUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );
        pnlFilterUsersLayout.setVerticalGroup(
            pnlFilterUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFilterUsersLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(vSearchBarUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(scrollUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFilterUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFilterUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlFilterUsers;
    private javax.swing.JScrollPane scrollUsers;
    private javax.swing.JTable tblUsers;
    private view.subViews.VSearchBarUsers vSearchBarUsers;
    // End of variables declaration//GEN-END:variables
}
