package view.payments;

/**
 *
 * @author kalei
 */
public class AddPayment extends javax.swing.JFrame {
    /**
     * Creates new form 
     */
    public AddPayment() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        sep01 = new javax.swing.JSeparator();
        pnlDue = new javax.swing.JPanel();
        txtDue = new javax.swing.JTextField();
        lblDue = new javax.swing.JLabel();
        sep02 = new javax.swing.JSeparator();
        pnlPmt = new javax.swing.JPanel();
        lblOr = new javax.swing.JLabel();
        btnPayAll = new javax.swing.JButton();
        pnlSelects = new javax.swing.JPanel();
        lblMethod = new javax.swing.JLabel();
        comboMethod = new javax.swing.JComboBox<>();
        lblStatus = new javax.swing.JLabel();
        comboStatus = new javax.swing.JComboBox<>();
        pnlAmount = new javax.swing.JPanel();
        lblAmount = new javax.swing.JLabel();
        txtAmt = new javax.swing.JTextField();
        btnPayPart = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Trip");

        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("New Payment");

        txtDue.addActionListener(this::txtDueActionPerformed);

        lblDue.setText("Total Amount Due: ");

        javax.swing.GroupLayout pnlDueLayout = new javax.swing.GroupLayout(pnlDue);
        pnlDue.setLayout(pnlDueLayout);
        pnlDueLayout.setHorizontalGroup(
            pnlDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDue, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlDueLayout.setVerticalGroup(
            pnlDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDue))
                .addContainerGap())
        );

        lblOr.setText("or");

        btnPayAll.setBackground(new java.awt.Color(204, 255, 204));
        btnPayAll.setText("Pay All");
        btnPayAll.addActionListener(this::btnPayAllActionPerformed);

        lblMethod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMethod.setText("Payment Method");

        comboMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Credit Card", "Debit Card", "PayPal" }));
        comboMethod.addActionListener(this::comboMethodActionPerformed);

        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setText("Payment Status");

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Paid", "Refunded", "Failed" }));
        comboStatus.addActionListener(this::comboStatusActionPerformed);

        javax.swing.GroupLayout pnlSelectsLayout = new javax.swing.GroupLayout(pnlSelects);
        pnlSelects.setLayout(pnlSelectsLayout);
        pnlSelectsLayout.setHorizontalGroup(
            pnlSelectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSelectsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSelectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboMethod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMethod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboStatus, 0, 101, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlSelectsLayout.setVerticalGroup(
            pnlSelectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSelectsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMethod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        lblAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAmount.setText("Amount");

        btnPayPart.setText("<html>Pay Partial &<br>Update Due</html>");
        btnPayPart.addActionListener(this::btnPayPartActionPerformed);

        javax.swing.GroupLayout pnlAmountLayout = new javax.swing.GroupLayout(pnlAmount);
        pnlAmount.setLayout(pnlAmountLayout);
        pnlAmountLayout.setHorizontalGroup(
            pnlAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAmountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAmt)
                    .addComponent(btnPayPart)
                    .addComponent(lblAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlAmountLayout.setVerticalGroup(
            pnlAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAmountLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblAmount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPayPart, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlPmtLayout = new javax.swing.GroupLayout(pnlPmt);
        pnlPmt.setLayout(pnlPmtLayout);
        pnlPmtLayout.setHorizontalGroup(
            pnlPmtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPmtLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnlSelects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnPayAll, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lblOr)
                .addGap(6, 6, 6)
                .addComponent(pnlAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        pnlPmtLayout.setVerticalGroup(
            pnlPmtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPmtLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlPmtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlSelects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPayAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPmtLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblOr)
                .addGap(68, 68, 68))
        );

        btnCancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlPmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sep02)
                    .addComponent(sep01, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sep01, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sep02, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlPmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDueActionPerformed

    private void btnPayAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPayAllActionPerformed

    private void btnPayPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayPartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPayPartActionPerformed

    private void comboMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMethodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMethodActionPerformed

    private void comboStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboStatusActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPayAll;
    private javax.swing.JButton btnPayPart;
    private javax.swing.JComboBox<String> comboMethod;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblDue;
    private javax.swing.JLabel lblMethod;
    private javax.swing.JLabel lblOr;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlAmount;
    private javax.swing.JPanel pnlDue;
    private javax.swing.JPanel pnlPmt;
    private javax.swing.JPanel pnlSelects;
    private javax.swing.JSeparator sep01;
    private javax.swing.JSeparator sep02;
    private javax.swing.JTextField txtAmt;
    private javax.swing.JTextField txtDue;
    // End of variables declaration//GEN-END:variables
}