package view.dashboard;

import java.awt.event.ActionListener;
import utility.AppContext;
import utility.GenericView;
import view.components.PanelBorder;
import view.dashboard.DashboardAdmin;

/**
 *
 * @author rowan
 */
public class AppWindowAdmin extends GenericView {
    
    public AppWindowAdmin( AppContext context ) {
        super( context );
        initComponents();
        pnlDashAdmin.revalidate();
        pnlDashAdmin.repaint();
        
//        this.session = session;
//        setBackground( new Color(0, 0, 0, 0) ); //only works with undecorated frame
    }
    
     //Getter and Setters
//    public DashboardAdmin getDashboardList() {
//        return pnlDashAdmin;
//    }
//    public void setDashboardList(DashboardAdmin pnlDashAdmin) {
//        this.pnlDashAdmin = pnlDashAdmin;
//    }
//
//    public PanelBorder getPnlAppWindow() {
//        return pnlDashWind;
//    }
//    public void setPnlAppWindow(PanelBorder pnlAppWindow) {
//        this.pnlDashWind = pnlAppWindow;
//    }

    public DashboardAdmin getPnlDashAdmin() {
        return pnlDashAdmin;
    }
    public void setPnlDashAdmin(DashboardAdmin pnlDashAdmin) {
        this.pnlDashAdmin = pnlDashAdmin;
    }

    public PanelBorder getPnlDashWind() {
        return pnlDashWind;
    }
    public void setPnlDashWind(PanelBorder pnlDashWind) {
        this.pnlDashWind = pnlDashWind;
    }
    
    // ---------------Listeners--------------------------
    //----------------Customer Section-------------------
    public void addListenerToBtnCustProfile( ActionListener listener ) {
        pnlDashAdmin.getPnlDashAgent().getPnlDashCust().getBtnCustProfile().addActionListener( listener ); }
    public void addListenerToBtnSearchDest( ActionListener listener ) {
        pnlDashAdmin.getPnlDashAgent().getPnlDashCust().getBtnSearchDest().addActionListener( listener ); }
    public void addListenerToBtnAllBooking( ActionListener listener ) {
        pnlDashAdmin.getPnlDashAgent().getPnlDashCust().getBtnViewBooking().addActionListener( listener ); }
        
    //----------------Agent Section-------------------
    public void addListenerToBtnAdminProfile( ActionListener listener ) {
        pnlDashAdmin.getPnlDashAgent().getBtnAgentProfile().addActionListener( listener ); }
    public void addListenerToBtnSearchCust( ActionListener listener ) {
        pnlDashAdmin.getPnlDashAgent().getBtnSearchCust().addActionListener( listener ); }
    public void addListenerToBtnLogoutAgent( ActionListener listener ) {
        pnlDashAdmin.getPnlDashAgent().getBtnLogout().addActionListener( listener ); }
    public void addListenerToBtnClearCust( ActionListener listener ) {
        pnlDashAdmin.getPnlDashAgent().getBtnClearCust().addActionListener( listener ); }
                
    //----------------Admin Section-------------------
    public void addListenerToBtnSearchDestAdmin( ActionListener listener ) {
        pnlDashAdmin.getPnlDashAdmin().getBtnDestinations().addActionListener( listener ); }
    public void addListenerToBtnSearchTrips( ActionListener listener ) {
        pnlDashAdmin.getPnlDashAdmin().getBtnTrips().addActionListener( listener ); }
    public void addListenerToBtnSearchBook( ActionListener listener ) {
        pnlDashAdmin.getPnlDashAdmin().getBtnBooking().addActionListener( listener ); }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDashWind = new view.components.PanelBorder();
        pnlDashAdmin = new view.dashboard.DashboardAdmin();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout pnlDashWindLayout = new javax.swing.GroupLayout(pnlDashWind);
        pnlDashWind.setLayout(pnlDashWindLayout);
        pnlDashWindLayout.setHorizontalGroup(
            pnlDashWindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashWindLayout.createSequentialGroup()
                .addComponent(pnlDashAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlDashWindLayout.setVerticalGroup(
            pnlDashWindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDashAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDashWind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDashWind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> {
//            
//            AppContext session = new AppContext();
//            AppWindow app = new AppWindow( session );
//            app.setVisible(true);
//            
//            /*temporary while working on things - add user GUI */
//            AddUserGUIPage1 view = new AddUserGUIPage1();
//            UserDAO userDao = new UserDAO();
//            UserControl userControl = new UserControl( userDao, view );
//            
//            view.setVisible(true);
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.dashboard.DashboardAdmin pnlDashAdmin;
    private view.components.PanelBorder pnlDashWind;
    // End of variables declaration//GEN-END:variables
}
