
package view.dashboard;

import javax.swing.JLabel;
import view.models.ButtonBase;

/**
 *
 * @author Mariah
 */
public class DashPanelCustomer extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public DashPanelCustomer() {
        initComponents();
    }

    public ButtonBase getBtnCustProfile() {
        return btnCustProfile;
    }

    public void setBtnCustProfile(ButtonBase btnCustProfile) {
        this.btnCustProfile = btnCustProfile;
    }

    public ButtonBase getBtnSearchDest() {
        return btnSearchDest;
    }

    public void setBtnSearchDest(ButtonBase btnSearchDest) {
        this.btnSearchDest = btnSearchDest;
    }

    public ButtonBase getLblLatestBooking() {
        return lblLatestBooking;
    }

    public void setLblLatestBooking(ButtonBase lblLatestBooking) {
        this.lblLatestBooking = lblLatestBooking;
    }

    public JLabel getLblUser() {
        return lblUser;
    }

    public void setLblUser(JLabel lblUser) {
        this.lblUser = lblUser;
    }

    public ButtonBase getLblViewBooking() {
        return lblViewBooking;
    }

    public void setLblViewBooking(ButtonBase lblViewBooking) {
        this.lblViewBooking = lblViewBooking;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUser = new javax.swing.JLabel();
        btnCustProfile = new view.models.ButtonBase();
        btnSearchDest = new view.models.ButtonBase();
        lblLatestBooking = new view.models.ButtonBase();
        lblViewBooking = new view.models.ButtonBase();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(350, 303));

        lblUser.setText("temp");

        btnCustProfile.setActionCommand("searchTrips");
        btnCustProfile.setLabel("My Profile");

        btnSearchDest.setActionCommand("searchTrips");
        btnSearchDest.setBackground(new java.awt.Color(255, 204, 153));
        btnSearchDest.setLabel("Search Destinations");

        lblLatestBooking.setActionCommand("LastBooking");
        lblLatestBooking.setLabel("Latest Booking");

        lblViewBooking.setActionCommand("AllBooking");
        lblViewBooking.setLabel("All Bookings");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCustProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearchDest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLatestBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblViewBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCustProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnSearchDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(lblLatestBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(lblViewBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.models.ButtonBase btnCustProfile;
    private view.models.ButtonBase btnSearchDest;
    private view.models.ButtonBase lblLatestBooking;
    private javax.swing.JLabel lblUser;
    private view.models.ButtonBase lblViewBooking;
    // End of variables declaration//GEN-END:variables
}
