/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.dashboard;

import javax.swing.JLabel;
import view.models.ButtonBase;

/**
 *
 * @author c0350261
 */
public class DashPanelAgent extends javax.swing.JPanel {

    /**
     * Creates new form DashPanelAgent
     */
    public DashPanelAgent() {
        initComponents();
    }

    public ButtonBase getBtnAgentProfile() {
        return btnAgentProfile;
    }

    public void setBtnAgentProfile(ButtonBase btnAgentProfile) {
        this.btnAgentProfile = btnAgentProfile;
    }

    public ButtonBase getBtnSearchCust() {
        return btnSearchCust;
    }

    public void setBtnSearchCust(ButtonBase btnSearchCust) {
        this.btnSearchCust = btnSearchCust;
    }

    public ButtonBase getLblClearCust() {
        return lblClearCust;
    }

    public void setLblClearCust(ButtonBase lblClearCust) {
        this.lblClearCust = lblClearCust;
    }

    public ButtonBase getLblLogout() {
        return lblLogout;
    }

    public void setLblLogout(ButtonBase lblLogout) {
        this.lblLogout = lblLogout;
    }

    public JLabel getLblUser() {
        return lblUser;
    }

    public void setLblUser(JLabel lblUser) {
        this.lblUser = lblUser;
    }

    public DashPanelCustomer getPnlDashCust() {
        return pnlDashCust;
    }

    public void setPnlDashCust(DashPanelCustomer pnlDashCust) {
        this.pnlDashCust = pnlDashCust;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUser = new javax.swing.JLabel();
        btnAgentProfile = new view.models.ButtonBase();
        btnSearchCust = new view.models.ButtonBase();
        lblLogout = new view.models.ButtonBase();
        pnlDashCust = new view.dashboard.DashPanelCustomer();
        lblClearCust = new view.models.ButtonBase();

        setOpaque(false);

        lblUser.setText("temp");

        btnAgentProfile.setActionCommand("searchTrips");
        btnAgentProfile.setLabel("My Profile");

        btnSearchCust.setActionCommand("searchCustomer");
        btnSearchCust.setBackground(new java.awt.Color(255, 204, 153));
        btnSearchCust.setLabel("Search Customers");

        lblLogout.setActionCommand("Logout");
        lblLogout.setBackground(new java.awt.Color(189, 238, 239));
        lblLogout.setLabel("Logout");

        lblClearCust.setActionCommand("ClearCust");
        lblClearCust.setBackground(new java.awt.Color(189, 238, 239));
        lblClearCust.setLabel("Clear Customer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearchCust, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(btnAgentProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblClearCust, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addComponent(pnlDashCust, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnAgentProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnSearchCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(pnlDashCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(lblClearCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.models.ButtonBase btnAgentProfile;
    private view.models.ButtonBase btnSearchCust;
    private view.models.ButtonBase lblClearCust;
    private view.models.ButtonBase lblLogout;
    private javax.swing.JLabel lblUser;
    private view.dashboard.DashPanelCustomer pnlDashCust;
    // End of variables declaration//GEN-END:variables
}
