/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.dashboard;

import javax.swing.JLabel;
import view.models.ButtonBase;

/**
 *
 * @author c0350261
 */
public class DashPanelAgent extends javax.swing.JPanel {

    /**
     * Creates new form DashPanelAgent
     */
    public DashPanelAgent() {
        initComponents();
    }

    public ButtonBase getBtnAgentProfile() {
        return btnAgentProfile;
    }

    public void setBtnAgentProfile(ButtonBase btnAgentProfile) {
        this.btnAgentProfile = btnAgentProfile;
    }

    public ButtonBase getBtnSearchCust() {
        return btnSearchCust;
    }

    public void setBtnSearchCust(ButtonBase btnSearchCust) {
        this.btnSearchCust = btnSearchCust;
    }

    public ButtonBase getBtnClearCust() {
        return btnClearCust;
    }

    public void setBtnClearCust(ButtonBase lblClearCust) {
        this.btnClearCust = lblClearCust;
    }

    public ButtonBase getBtnLogout() {
        return btnLogout;
    }

    public void setBtnLogout(ButtonBase lblLogout) {
        this.btnLogout = lblLogout;
    }

    public JLabel getLblUser() {
        return lblUser;
    }

    public void setLblUser(JLabel lblUser) {
        this.lblUser = lblUser;
    }

    public DashPanelCustomer getPnlDashCust() {
        return pnlDashCust;
    }

    public void setPnlDashCust(DashPanelCustomer pnlDashCust) {
        this.pnlDashCust = pnlDashCust;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUser = new javax.swing.JLabel();
        btnAgentProfile = new view.models.ButtonBase();
        btnSearchCust = new view.models.ButtonBase();
        btnLogout = new view.models.ButtonBase();
        pnlDashCust = new view.dashboard.DashPanelCustomer();
        btnClearCust = new view.models.ButtonBase();

        setOpaque(false);

        lblUser.setText("temp");

        btnAgentProfile.setActionCommand("searchTrips");
        btnAgentProfile.setLabel("My Profile");

        btnSearchCust.setActionCommand("searchCustomer");
        btnSearchCust.setBackground(new java.awt.Color(255, 204, 153));
        btnSearchCust.setLabel("Search Customers");

        btnLogout.setActionCommand("Logout");
        btnLogout.setBackground(new java.awt.Color(189, 238, 239));
        btnLogout.setLabel("Logout");

        btnClearCust.setActionCommand("ClearCust");
        btnClearCust.setBackground(new java.awt.Color(189, 238, 239));
        btnClearCust.setLabel("Clear Customer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearchCust, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(btnAgentProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClearCust, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addComponent(pnlDashCust, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnAgentProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnSearchCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(pnlDashCust, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClearCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.models.ButtonBase btnAgentProfile;
    private view.models.ButtonBase btnClearCust;
    private view.models.ButtonBase btnLogout;
    private view.models.ButtonBase btnSearchCust;
    private javax.swing.JLabel lblUser;
    private view.dashboard.DashPanelCustomer pnlDashCust;
    // End of variables declaration//GEN-END:variables
}
