package view.dashboard;

import utility.AppContext;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;
import view.components.GradientPanel;

/**
 *
 * @author rowan
 */
public class DashboardAgent extends GradientPanel {
        Color topColor;
        Color bottomColor;
        Color selectColor;
//        private AppContext context;
        private AppWindowCust topView;
        private AppContext context;
//        ListMenu menuList = new ListMenu();


    /**
     * Creates new form MenuCustomer
     */
    public DashboardAgent( ) {
        super(new Color(204,255,204), new Color( 255,150,46 ), 0);
        initComponents();
    }
        
    //getters and setters

    public AppWindowCust getTopView() { return topView; }
    public void setTopView(AppWindowCust topView) { 
        this.topView = topView; 
    }

    public JLabel getLblLogo() { return lblLogo; }
    public void setLblLogo(JLabel lblLogo) {
        this.lblLogo = lblLogo;
    }
    
    public DashPanelAgent getDashPanel(){ return dashPanelAgent; }
    public void DashPanelAgent( DashPanelAgent panel ){ this.dashPanelAgent = panel; }

    public JPanel getPnlLogo() { return pnlLogo; }
    public void setPnlLogo(JPanel pnlLogo) {
        this.pnlLogo = pnlLogo;
    }

    public DashPanelAgent getDashPanelAgent() {
        return dashPanelAgent;
    }

    public void setDashPanelAgent(DashPanelAgent dashPanelAgent) {
        this.dashPanelAgent = dashPanelAgent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        dashPanelAgent = new view.dashboard.DashPanelAgent();

        pnlLogo.setOpaque(false);

        lblLogo.setFont(new java.awt.Font("URW Bookman", 1, 36)); // NOI18N
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/dashboard/travelBug70.png"))); // NOI18N
        lblLogo.setText("Travel Bug");

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dashPanelAgent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(dashPanelAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 550, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.dashboard.DashPanelAgent dashPanelAgent;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel pnlLogo;
    // End of variables declaration//GEN-END:variables
}
