package view.dashboard;

import utility.AppContext;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;
import view.components.GradientPanel;
import view.models.ButtonBase;

/**
 *
 * @author rowan
 */
public class DashboardCustomer extends GradientPanel {
        Color topColor;
        Color bottomColor;
        Color selectColor;
        private AppWindowCust topView;
        private AppContext context;

    /**
     * Creates new form MenuCustomer
     */
    public DashboardCustomer( ) {
        super(new Color(204,255,204), new Color( 255,150,46 ), 0);
        initComponents();
    }
        
    //getters and setters

    public AppWindowCust getTopView() { return topView; }
    public void setTopView(AppWindowCust topView) { 
        this.topView = topView; 
    }

    public JLabel getLblLogo() { return lblLogo; }
    public void setLblLogo(JLabel lblLogo) {
        this.lblLogo = lblLogo;
    }
    
    public JPanel getPnlLogo() { return pnlLogo; }
    public void setPnlLogo(JPanel pnlLogo) {
        this.pnlLogo = pnlLogo;
    }       

    public DashPanelCustomer getPnlDashCust() {
        return pnlDashCust;
    }

    public void setPnlDashCust(DashPanelCustomer pnlDashCust) {
        this.pnlDashCust = pnlDashCust;
    }

    public ButtonBase getBtnLogout() {
        return btnLogout;
    }

    public void setBtnLogout(ButtonBase btnLogout) {
        this.btnLogout = btnLogout;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btnLogout = new view.models.ButtonBase();
        pnlDashCust = new view.dashboard.DashPanelCustomer();

        pnlLogo.setOpaque(false);

        lblLogo.setFont(new java.awt.Font("URW Bookman", 1, 36)); // NOI18N
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/graphics/travelBug70.png"))); // NOI18N
        lblLogo.setText("Travel Bug");

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        btnLogout.setActionCommand("Logout");
        btnLogout.setBackground(new java.awt.Color(189, 238, 239));
        btnLogout.setLabel("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlDashCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(pnlDashCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.models.ButtonBase btnLogout;
    private javax.swing.JLabel lblLogo;
    private view.dashboard.DashPanelCustomer pnlDashCust;
    private javax.swing.JPanel pnlLogo;
    // End of variables declaration//GEN-END:variables
}
