package view.dashboard;

import utility.AppContext;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;
import model.User;
import view.ViewCustomerGUI;
import view.ViewDestinationsGUI;
import view.ViewTripFrame;
import utility.AppWindowCust;
import view.components.GradientPanel;
import view.components.ListMenu;

/**
 *
 * @author rowan
 */
public class DashboardCustomer extends GradientPanel {
        Color topColor;
        Color bottomColor;
        Color selectColor;
//        private AppContext context;
        private AppWindowCust topView;
        private AppContext context;
//        ListMenu menuList = new ListMenu();


    /**
     * Creates new form MenuCustomer
     */
    public DashboardCustomer( ) {
        super(new Color(204,255,204), new Color( 255,150,46 ), 0);
        initComponents();
        
//        menuListB.setOpaque(false);
//        menuListB.refresh();
//        menuListB.setVisible(true);
//        
//        menuListA.setOpaque(false);
//        menuListA.refresh();
//        menuListA.setVisible(true);
    }
        
    //getters and setters

    public AppWindowCust getTopView() { return topView; }
    public void setTopView(AppWindowCust topView) { 
        this.topView = topView; 
    }

    public JLabel getLblLogo() { return lblLogo; }
    public void setLblLogo(JLabel lblLogo) {
        this.lblLogo = lblLogo;
    }

//    public ListMenu getMenuListA() { return menuListB; }
//    public void setMenuListA(ListMenu menuList) {
//        this.menuListB = menuList;
//    }
//    public ListMenu getMenuListB() { return menuListA; }
//    public void setMenuListB(ListMenu menuList) {
//        this.menuListA = menuList;
//    }

    public JPanel getPnlLogo() { return pnlLogo; }
    public void setPnlLogo(JPanel pnlLogo) {
        this.pnlLogo = pnlLogo;
    }       
    
//    public void setBasics(AppWindowCust topView, AppContext context) {
//    this.topView = topView;
//    this.context = context;
//    repaint();
//    }


//    public ListMenu<String> getListMenuCustomer() {
//        return menuList;
//    }
//
//    public void setListMenuCustomer(ListMenu<String> menuList) {
//        this.menuList = menuList;
//    }
    

// FUNCTIONAL

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        dashPanelCustomer1 = new view.dashboard.DashPanelCustomer();

        pnlLogo.setOpaque(false);

        lblLogo.setFont(new java.awt.Font("URW Bookman", 1, 36)); // NOI18N
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/graphics/travelBug70.png"))); // NOI18N
        lblLogo.setText("Travel Bug");

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dashPanelCustomer1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dashPanelCustomer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

//    @Override
//    protected void paintChildren(Graphics grphcs){
//        Graphics2D g2 = (Graphics2D)grphcs;
//        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
//        GradientPaint g=new GradientPaint(0, 0, Color.decode(gradientTop), 0, getHeight(), Color.decode(gradientBottom));
//        g2.setPaint(g);
    ////        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
//        g2.fillRect(0, 0, getWidth(), getHeight());
//        
//        super.paintChildren(grphcs);
//    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.dashboard.DashPanelCustomer dashPanelCustomer1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel pnlLogo;
    // End of variables declaration//GEN-END:variables
}
