package view.dashboard;

import utility.AppContext;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;
import view.components.GradientPanel;

/**
 *
 * @author rowan
 */
public class DashboardAdmin extends GradientPanel {
        Color topColor;
        Color bottomColor;
        Color selectColor;
        private AppWindowCust topView;
        private AppContext context;

    /**
     * Creates new form MenuCustomer
     */
    public DashboardAdmin( ) {
        super(new Color(204,255,204), new Color( 255,150,46 ), 0);
        initComponents();
    }
        
    //getters and setters

    public AppWindowCust getTopView() { return topView; }
    public void setTopView(AppWindowCust topView) { 
        this.topView = topView; 
    }

    public JLabel getLblLogo() { return lblLogo; }
    public void setLblLogo(JLabel lblLogo) {
        this.lblLogo = lblLogo;
    }

    public JPanel getPnlLogo() { return pnlLogo; }
    public void setPnlLogo(JPanel pnlLogo) {
        this.pnlLogo = pnlLogo;
    }

    public DashPanelAdmin getPnlDashAdmin() {
        return pnlDashAdmin;
    }

    public void setPnlDashAdmin(DashPanelAdmin pnlDashAdmin) {
        this.pnlDashAdmin = pnlDashAdmin;
    }

    public DashPanelAgent getPnlDashAgent() {
        return pnlDashAgent;
    }

    public void setPnlDashAgent(DashPanelAgent pnlDashAgent) {
        this.pnlDashAgent = pnlDashAgent;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlDashAgent = new view.dashboard.DashPanelAgent();
        pnlDashAdmin = new view.dashboard.DashPanelAdmin();

        pnlLogo.setOpaque(false);

        lblLogo.setFont(new java.awt.Font("URW Bookman", 1, 36)); // NOI18N
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/dashboard/travelBug70.png"))); // NOI18N
        lblLogo.setText("Travel Bug");

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDashAgent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDashAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(pnlDashAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlDashAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLogo;
    private view.dashboard.DashPanelAdmin pnlDashAdmin;
    private view.dashboard.DashPanelAgent pnlDashAgent;
    private javax.swing.JPanel pnlLogo;
    // End of variables declaration//GEN-END:variables
}
