package view.dashboard;

import javax.swing.JLabel;
import view.models.ButtonBase;

/**
 *
 * @author Mariah
 */
public class DashPanelAdmin extends javax.swing.JPanel {

    /**
     * Creates new form DashPanelAgent
     */
    public DashPanelAdmin() {
        initComponents();
    }

    public ButtonBase getBtnBooking() {
        return btnBooking;
    }

    public void setBtnBooking(ButtonBase btnBooking) {
        this.btnBooking = btnBooking;
    }

    public ButtonBase getBtnDestinations() {
        return btnDestinations;
    }

    public void setBtnDestinations(ButtonBase btnDestinations) {
        this.btnDestinations = btnDestinations;
    }

    public ButtonBase getBtnPackages() {
        return btnPackages;
    }

    public void setBtnPackages(ButtonBase btnPackages) {
        this.btnPackages = btnPackages;
    }
//
//    public ButtonBase getBtnProducts() {
//        return btnProducts;
//    }
//
//    public void setBtnProducts(ButtonBase btnProducts) {
//        this.btnProducts = btnProducts;
//    }

//    public ButtonBase getBtnTrips() {
//        return btnTrips;
//    }
//
//    public void setBtnTrips(ButtonBase btnTrips) {
//        this.btnTrips = btnTrips;
//    }

    public JLabel getLblUser() {
        return lblUser;
    }

    public void setLblUser(JLabel lblUser) {
        this.lblUser = lblUser;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPackages = new view.models.ButtonBase();
        lblUser = new javax.swing.JLabel();
        btnBooking = new view.models.ButtonBase();
        btnDestinations = new view.models.ButtonBase();

        setOpaque(false);

        btnPackages.setActionCommand("searchPackages");
        btnPackages.setLabel("Packages");
        btnPackages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPackagesActionPerformed(evt);
            }
        });

        lblUser.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblUser.setText("Search & Edit");

        btnBooking.setActionCommand("searchBooking");
        btnBooking.setLabel("Booking");
        btnBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingActionPerformed(evt);
            }
        });

        btnDestinations.setActionCommand("searchDestinations");
        btnDestinations.setLabel("Destinations");
        btnDestinations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDestinationsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDestinations, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(btnPackages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnPackages, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnDestinations, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPackagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPackagesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPackagesActionPerformed

    private void btnBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBookingActionPerformed

    private void btnDestinationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDestinationsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDestinationsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.models.ButtonBase btnBooking;
    private view.models.ButtonBase btnDestinations;
    private view.models.ButtonBase btnPackages;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
