package view.Person;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author rowan
 */
public class PersonDash extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PersonDash.class.getName());

    /**
     * Creates new form UserView
     */
    public PersonDash() {
        initComponents();
    }
    
    
    //setters & getters: button
    public JButton getBtnAdd() { return btnAdd; }
    public void setBtnAdd(JButton btnAdd) { this.btnAdd = btnAdd; }
    
    public JButton getBtnFind() { return btnFind1; }
    public void setBtnFind(JButton btnFind1) { this.btnFind1 = btnFind1; }
    
    public JButton getBtnFindMany() { return btnFindMany; }
    public void setBtnFindMany(JButton btnFindMany) { this.btnFindMany = btnFindMany; }

    public JButton getBtnLuggage() { return btnLuggage; }
    public void setBtnLuggage(JButton btnLuggage) { this.btnLuggage = btnLuggage; }
    
    //listeners
    public void addPersonBtnListener(ActionListener addListener){
        btnAdd.addActionListener(addListener);
    }
    public void findPersonBtnListener(ActionListener findListener){
        btnFind1.addActionListener(findListener);
    }
    public void findPeopleBtnListener(ActionListener findManyListener){
        btnFindMany.addActionListener(findManyListener);
    }
    public void findLuggageBtnListener(ActionListener findLuggageListener){
        btnLuggage.addActionListener(findLuggageListener);
    }
    
    //helpers
    public void clearFields() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JButton();
        btnFind1 = new javax.swing.JButton();
        btnFindMany = new javax.swing.JButton();
        btnLuggage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAdd.setText("Add");

        btnFind1.setText("Find");

        btnFindMany.setText("Find Many");

        btnLuggage.setText("Luggage");
        btnLuggage.addActionListener(this::btnLuggageActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLuggage, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindMany, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFind1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFindMany, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLuggage, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuggageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuggageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLuggageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnFind1;
    private javax.swing.JButton btnFindMany;
    private javax.swing.JButton btnLuggage;
    // End of variables declaration//GEN-END:variables
}
