/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.subViews;

/**
 *
 * @author C0350261
 */
public class VEmergencyContact extends javax.swing.JPanel {

    /**
     * Creates new form eEmergencyContact
     */
    public VEmergencyContact() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEmergencyContact = new javax.swing.JPanel();
        lblEmergContact = new javax.swing.JLabel();
        txtEmergencyBlock = new javax.swing.JTextField();

        lblEmergContact.setLabelFor(txtEmergencyBlock);
        lblEmergContact.setText("Emergency Contact Information");

        txtEmergencyBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmergencyBlockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEmergencyContactLayout = new javax.swing.GroupLayout(pnlEmergencyContact);
        pnlEmergencyContact.setLayout(pnlEmergencyContactLayout);
        pnlEmergencyContactLayout.setHorizontalGroup(
            pnlEmergencyContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmergencyContactLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEmergencyContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlEmergencyContactLayout.createSequentialGroup()
                        .addComponent(lblEmergContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(69, 69, 69))
                    .addComponent(txtEmergencyBlock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEmergencyContactLayout.setVerticalGroup(
            pnlEmergencyContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmergencyContactLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEmergContact)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmergencyBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEmergencyContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlEmergencyContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmergencyBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmergencyBlockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmergencyBlockActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblEmergContact;
    private javax.swing.JPanel pnlEmergencyContact;
    private javax.swing.JTextField txtEmergencyBlock;
    // End of variables declaration//GEN-END:variables
}
