/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.subViews;

/**
 *
 * @author C0350261
 */
public class vActivities extends javax.swing.JPanel {

    /**
     * Creates new form vActivities
     */
    public vActivities() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlActivities = new javax.swing.JPanel();
        lblActivities = new javax.swing.JLabel();
        txtActivitiesIncl = new javax.swing.JTextField();
        txtActivitiesOption = new javax.swing.JTextField();

        pnlActivities.setBackground(new java.awt.Color(255, 204, 153));

        lblActivities.setText("Activities");

        txtActivitiesIncl.setText("included activities");

        txtActivitiesOption.setText("optional activities");

        javax.swing.GroupLayout pnlActivitiesLayout = new javax.swing.GroupLayout(pnlActivities);
        pnlActivities.setLayout(pnlActivitiesLayout);
        pnlActivitiesLayout.setHorizontalGroup(
            pnlActivitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActivitiesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlActivitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtActivitiesIncl)
                    .addGroup(pnlActivitiesLayout.createSequentialGroup()
                        .addComponent(lblActivities)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtActivitiesOption))
                .addContainerGap())
        );
        pnlActivitiesLayout.setVerticalGroup(
            pnlActivitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActivitiesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblActivities)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtActivitiesIncl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtActivitiesOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlActivities, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlActivities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblActivities;
    private javax.swing.JPanel pnlActivities;
    private javax.swing.JTextField txtActivitiesIncl;
    private javax.swing.JTextField txtActivitiesOption;
    // End of variables declaration//GEN-END:variables
}
