/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.subViews;

import java.awt.event.ActionListener;

/**
 *
 * @author C0350261
 */
public class VAddress extends javax.swing.JPanel {

    /**
     * Creates new form vHotelInfo
     */
    public VAddress() {
        initComponents();
    }
    
    public String getAddressText() { return txtFullAddress.getText(); } // get current content?
    public void onSubmit(ActionListener listener) {
    }
    public void updateAddressText(String text) {
        txtFullAddress.setText( text );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAddressBlock = new javax.swing.JPanel();
        txtFullAddress = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();

        pnlAddressBlock.setBackground(new java.awt.Color(255, 204, 153));

        lblAddress.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        lblAddress.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAddress.setLabelFor(txtFullAddress);
        lblAddress.setText("Address");
        lblAddress.setToolTipText("");

        javax.swing.GroupLayout pnlAddressBlockLayout = new javax.swing.GroupLayout(pnlAddressBlock);
        pnlAddressBlock.setLayout(pnlAddressBlockLayout);
        pnlAddressBlockLayout.setHorizontalGroup(
            pnlAddressBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddressBlockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddressBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFullAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                    .addComponent(lblAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlAddressBlockLayout.setVerticalGroup(
            pnlAddressBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddressBlockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFullAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAddressBlock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAddressBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAddress;
    private javax.swing.JPanel pnlAddressBlock;
    private javax.swing.JTextField txtFullAddress;
    // End of variables declaration//GEN-END:variables
}
