/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.subViews;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author rowan
 */
public class VSearchBarUsers extends javax.swing.JPanel {

    /**
     * Creates new form vSearchBar
     */
    public VSearchBarUsers() {
        initComponents();
    }

    public JButton getBtnNewUser() {
        return btnNewUser;
    }

    public void setBtnNewUser(JButton btnNewUser) {
        this.btnNewUser = btnNewUser;
    }

    public JButton getBtnSearch() {
        return btnSearch;
    }

    public void setBtnSearch(JButton btnSearch) {
        this.btnSearch = btnSearch;
    }

    public JComboBox<String> getComboUserRole() {
        return comboUserRole;
    }

    public void setComboUserRole(JComboBox<String> comboUserRole) {
        this.comboUserRole = comboUserRole;
    }

    public JTextField getTxtSearchField() {
        return txtSearchField;
    }

    public void setTxtSearchField(JTextField txtSearchField) {
        this.txtSearchField = txtSearchField;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearchField = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        comboUserRole = new javax.swing.JComboBox<>();
        btnNewUser = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(483, 35));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 35));

        txtSearchField.setToolTipText("Search users...");
        txtSearchField.addActionListener(this::txtSearchFieldActionPerformed);

        btnSearch.setBackground(new java.awt.Color(204, 255, 204));
        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        comboUserRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All roles", "Admin", "Agent", "Tour guide", "Customer" }));

        btnNewUser.setBackground(new java.awt.Color(51, 51, 51));
        btnNewUser.setForeground(new java.awt.Color(255, 255, 255));
        btnNewUser.setText("new");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboUserRole, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnNewUser)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(comboUserRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewUser))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchFieldActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewUser;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> comboUserRole;
    private javax.swing.JTextField txtSearchField;
    // End of variables declaration//GEN-END:variables
}
