package view.models;

import java.awt.Color;
import view.components.GradientPanel;

/**
 *
 * @author rowan
 */
public class Card extends GradientPanel {
    //Check if theres a significant preformance hit to doing things this way for plain background items
    private String title;
    private String contents;
    private CardType type;
    public static enum CardType { HEADER, ICON_HEADER, EMPTY, SEPARATOR, IMG, MENU }
    private int padding;
    private String tag;
    
    public Card(Color topColor, Color bottomColor, int roundCorners ) { //gradient background
        super(topColor, bottomColor, roundCorners);
    }
    
    public Card(Color bgColor, int roundCorners ) { //flat background
        super(bgColor, roundCorners);
    }        

    public Card() {
        this( new Color(255,255,255), 0 ); //white background
    }
         
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }

    public String getContents() { return contents; }
    public void setContents(String contents) { this.contents = contents;} 

    public int getPadding() { return padding; }
    public void setPadding(int padding) { this.padding = padding; }
    
    public CardType getType() { return type; }
    public void setType(CardType type) { this.type = type; }
    
    public String tag() { return tag; }
    public void setTag() { this.tag = tag; }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
