package view.models;

import java.awt.Color;
import java.awt.FontMetrics;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author rowan
 */
public class ImgCard extends Card {
    //Check if theres a significant preformance hit to doing things this way for plain background items
    //Clean up use of icon and imgName
    String icon;
    String imgName;
    ImgLocation imgLocation;
    public static enum ImgLocation { TOP, LEFT, BOTTOM, RIGHT, CENTER, EMPTY } 
    
    public ImgCard(Color topColor, Color bottomColor, int roundCorners ) { //gradient background
        super(topColor, bottomColor, roundCorners);
    }
    
    public ImgCard(Color bgColor, int roundCorners ) { //flat background
        super(bgColor, roundCorners);
    }        

    public ImgCard() {
        this( new Color(255,255,255), 0 ); //white background
    }
         
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public String getImgName() { return imgName; }
    public void setImgName(String imgName) { this.imgName = imgName; }

    public ImgLocation getImgLocation() {
        return imgLocation;
    }
    public void setImgLocation(ImgLocation imgLocation) {
        this.imgLocation = imgLocation;
    }
    
    public int getContentsHeight(JLabel label) {
        FontMetrics cFont = label.getFontMetrics( label.getFont() );
        int cFontHeight = cFont.getHeight();
        
        Icon cIcon = label.getIcon();
        int cIconHeight = cIcon.getIconHeight();
        
        int tallest = Math.max(cIconHeight, cFontHeight);

        return tallest;
    }
    
    public Icon toIcon() {
        return new ImageIcon(getClass().getResource("/view/graphics/" + icon + ".png"));
    }    

    public Icon toRoImageIcon() {
        return new RoImageIcon( getClass().getResource("/view/graphics/" + icon + ".png") );
    }
    
    public Icon toIcon(String icon) {
        return new ImageIcon(getClass().getResource("/view/graphics/" + icon + ".png"));
    }
    
    /**
    *
    * resizes icon to height x ? PIXELS; obeys original aspect ratio
    * SCALE_SMOOTH -> better image quality
    * SCALE_AREA_AVERAGING -> sharper image, may be better for small icons
    */
    public Icon scaleIconHeight(int height, String icon) {
        ImageIcon ogIcon = (ImageIcon) toIcon(icon);
        
        int ogHeight = ogIcon.getIconHeight();
        int ogWidth = ogIcon.getIconWidth();
        // not using aspect ratio so that less affected by int shortening
        int finalWidth = ( height * ogWidth ) / ogHeight;
//        double aspectRatio = (double) width / height;
        
        Image scaled = ogIcon.getImage().getScaledInstance( finalWidth, height, java.awt.Image.SCALE_AREA_AVERAGING);
        
        return new ImageIcon(scaled);
    }
    
    /**
    *
    * finds font size
    * input is the label with the relevant text
    */
    public int getFontHeight(JLabel label) {
        FontMetrics fontMetrics = label.getFontMetrics(label.getFont());      
        return fontMetrics.getHeight();
    }
   
    /**
    *
    * resizes icon to match font size; does NOT obey aspect ratio
    * input is the label with the relevant text
    */
    public Icon scaleIconByText(JLabel label, String icon) {
        ImageIcon ogIcon = (ImageIcon) toIcon(icon);
        int textSize = getFontHeight(label);
        
        ImageIcon scaled = (ImageIcon) scaleIconHeight(textSize, icon);
        
        return scaled;
    }
}  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


/**
 * what AI recommended: note use of Img and ImgIcon classes
 *             try {
                // 2. Load the source image (Replace with your own file or URL)
                URL url = new URL("https://picsum.photos");
                Image sourceImage = ImageIO.read(url);

                // 3. Calculate text height using FontMetrics
                FontMetrics metrics = label.getFontMetrics(label.getFont());
                int textHeight = metrics.getHeight(); // This is your target height

                // 4. Scale the image proportionally to match the text height
                // (Using -1 for width preserves the original aspect ratio)
                Image scaledImage = sourceImage.getScaledInstance(-1, textHeight, Image.SCALE_SMOOTH);

                // 5. Wrap the scaled image back into an Icon and apply it
                Icon finalIcon = new ImageIcon(scaledImage);
                label.setIcon(finalIcon);

            } catch (IOException e) {
                System.err.println("Could not load image: " + e.getMessage());
            }
 */